# Key = language code, value = text
declare -A texts
texts["en_ping_success"]="Internet connection established."
texts["ru_ping_success"]="Интернет соединение установлено."
texts["en_ping_fail"]="No Internet connection! Please connect to the Internet and run the script again."
texts["ru_ping_fail"]="Отсутствует интернет соединение! Пожалуйста, подключитесь к интернету и запустите скрипт снова."
texts["en_server_success"]="The connection to the server is established."
texts["ru_server_success"]="Соединение с сервером установлено."
texts["en_server_fail"]="No connection to Valve server! Your ISP has probably blocked Valve's servers. Try connecting to another network or using a VPN (or other blocking methods)."
texts["ru_server_fail"]="Отсутствует соединение с сервером Valve! Вероятно, ваш провайдер заблокировал сервера Valve. Попробуйте подключиться к другой сети или использовать VPN(или иные способы обхода блокировок)."
texts["en_integrity_fail"]="SDWEAK integrity violated, files corrupted or deleted! Reinstall SDWEAK!"
texts["ru_integrity_fail"]="Нарушена целостность SDWEAK, файлы повреждены или удалены! Переустановите SDWEAK!"
texts["en_compatible"]="SDWEAK is compatible with Steam Deck only!"
texts["ru_compatible"]="SDWEAK совместим только со Steam Deck!"
texts["en_old_steamos"]="SDWEAK is only compatible with SteamOS 3.7!"
texts["ru_old_steamos"]="SDWEAK совместим только с SteamOS 3.7!"
texts["en_installation_start"]="SDWEAK installation begins..."
texts["ru_installation_start"]="Начинается установка SDWEAK..."
texts["en_error_sys"]="A serious error has occurred! The system is corrupted, SDWEAK cannot be installed. Try updating the system to the beta version or call for help. TG: @noncatt"
texts["ru_error_sys"]="Произошла серьезная ошибка! Система повреждена, установка SDWEAK невозможна. Попробуйте обновить систему на бета версию или обратитесь за помощью. TG: @noncatt"
texts["en_skip"]="Skipping..."
texts["ru_skip"]="Пропуск..."
texts["en_invalid_input"]="Invalid input. Please enter 'y' or 'n'."
texts["ru_invalid_input"]="Неправильный ввод. Пожалуйста, введите 'y' или 'n'."
texts["en_bundled_package_missing"]="Critical Error: Bundled package for '$pkg_name' not found in ./packages/"
texts["ru_bundled_package_missing"]="Критическая ошибка: Пакет для '$pkg_name' не найден в ./packages/"

texts["en_yet_mglru"]="MGLRU successfully activated."
texts["ru_yet_mglru"]="MGLRU успешно активирован."
texts["en_yet_input"]="Input controller overclocking successfully activated."
texts["ru_yet_input"]="Разгон контроллера ввода успешно активирован."
texts["en_yet_services"]="Unnecessary services have been successfully disabled."
texts["ru_yet_services"]="Ненужные службы успешно отключены."
texts["en_ananicy_install"]="Installing Ananicy-cpp and the rules for it..."
texts["ru_ananicy_install"]="Установка Ananicy-cpp и правил для него..."
texts["en_daemon_ananicy"]="Ananicy-cpp and the rules for it have been successfully installed."
texts["ru_daemon_ananicy"]="Ananicy-cpp и правила для него успешно установлены."
texts["en_sysfs_optimization"]="Optimized sysfs parameters have been applied."
texts["ru_sysfs_optimization"]="Оптимизированные параметры sysfs применены."
texts["en_zram_conf"]="Optimal ZRAM settings have been successfully set."
texts["ru_zram_conf"]="Оптимальные настройки ZRAM успешно установлены."

texts["en_frametime_fix_prompt"]="Install a fix for uneven frametime when using FPS limiting via QAM? (BETA)"
texts["ru_frametime_fix_prompt"]="Установить исправление неровного фреймтайма при использовании ограничения FPS через QAM? (БЕТА)"
texts["en_frametime_fix_install"]="Installing a fix for uneven frametime..."
texts["ru_frametime_fix_install"]="Установка исправления неровного фреймтайма..."
texts["en_frametime_fix_success"]="Fix for uneven frametime has been successfully installed."
texts["ru_frametime_fix_success"]="Исправление неровного фреймтайма успешно установлено."

texts["en_display_overclock_prompt"]="Increase screen refresh rate to 70Hz?"
texts["ru_display_overclock_prompt"]="Поднять частоту обновления экрана до 70Hz?"
texts["en_display_overclock_success"]="Screen refresh rate successfully increased to 70Hz."
texts["ru_display_overclock_success"]="Частота обновления экрана успешно поднята до 70Hz."

texts["en_power_efficiency_prompt"]="Set CPU power efficiency priority?"
texts["ru_power_efficiency_prompt"]="Установить приоритет энергоэффективности для CPU?"
texts["en_power_efficiency_install"]="Applying CPU power efficiency priority..."
texts["ru_power_efficiency_install"]="Установка приоритета энергоэффективности..."
texts["en_power_efficiency_success"]="CPU power efficiency priority successfully applied."
texts["ru_power_efficiency_success"]="Приоритет энергоэффективности CPU успешно установлен."

texts["en_sdkernel_prompt"]="Install optimized kernel?"
texts["ru_sdkernel_prompt"]="Установить оптимизированное ядро?"
texts["en_sdkernel_install"]="Installing an optimized kernel..."
texts["ru_sdkernel_install"]="Установка оптимизированного ядра..."
texts["en_sdkernel_success"]="Optimized kernel has been successfully installed."
texts["ru_sdkernel_success"]="Оптимизированное ядро успешно установлено."

texts["en_gpu_optimization_prompt"]="Apply GPU driver optimizations?"
texts["ru_gpu_optimization_prompt"]="Применить оптимизации драйвера GPU?"
texts["en_gpu_optimization_success"]="GPU driver optimizations have been successfully applied."
texts["ru_gpu_optimization_success"]="Оптимизации драйвера GPU успешно применены."

texts["en_sdweak_success"]="SDWEAK installation completed successfully! If you like SDWEAK, you can support its development via the link in the repository on GITHUB. Thank you for using it!"
texts["ru_sdweak_success"]="Установка SDWEAK успешно завершена! Если вам нравится SDWEAK, вы можете поддержать его разработку по ссылке в репозитории на GITHUB. Спасибо за использование SDWEAK!"

texts["en_installation_time"]="Installation completed in"
texts["ru_installation_time"]="Установка завершена за"
texts["en_seconds"]="seconds."
texts["ru_seconds"]="секунды."

texts["en_reboot_prompt"]="Reboot to apply changes?"
texts["ru_reboot_prompt"]="Перезагрузить для применения изменений?"
texts["en_reboot_required"]="A reboot is required!"
texts["ru_reboot_required"]="Обязательно выполните перезагрузку!"
